# Generated by Django 6.0.6 on 2026-06-15 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HVACTripSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('ambient_temp_f', models.FloatField()),
                ('cabin_start_temp_f', models.FloatField()),
                ('target_temp_f', models.FloatField()),
                ('vent_temp_min_f', models.FloatField()),
                ('time_to_target_min', models.FloatField()),
                ('compressor_duty_avg', models.FloatField()),
                ('pressure_stability', models.FloatField()),
                ('fault_code_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=32, unique=True)),
                ('model', models.CharField(max_length=80)),
                ('model_year', models.PositiveSmallIntegerField()),
                ('region', models.CharField(max_length=40)),
                ('hvac_software_version', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HVACHealthAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_score', models.PositiveSmallIntegerField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16)),
                ('likely_issue', models.CharField(max_length=80)),
                ('confidence', models.FloatField()),
                ('recommended_action', models.CharField(max_length=80)),
                ('customer_message', models.TextField()),
                ('dealer_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='hvac.hvactripsummary')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hvac_assessments', to='hvac.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('customer', 'Customer'), ('dealer', 'Dealer'), ('oem', 'OEM')], max_length=16)),
                ('message', models.TextField()),
                ('should_send', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hvac.hvachealthassessment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='hvactripsummary',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hvac_trips', to='hvac.vehicle'),
        ),
    ]
